### ISSUE TITLE
plugin is not properly prepared for localization

### ISSUE THREAD

**Issue by Grimmwicht** [nickcernis/GNU-Terry-Pratchett#5]
Hi,

Wordpress.org states that this plugin is not properly prepared for localization: https://translate.wordpress.org/projects/wp-plugins/gnu-terry-pratchett

I guess this could easily be solved by adding
`* Text Domain: gnu-terry-pratchett`
directly in the main file under
`* Plugin Name: GNU Terry Pratchett`

The plugin itself obviously doesn't need localisation since it doesn't output any text, but there are many strings in the readme and plugin description on wordpress.org.

**Comment by nickcernis** [comment]
Thanks for the report, @Grimmwicht! I omitted it because there are no strings to translate just as you say, but will add this in the next release for localisation via WP.org.

**Comment by Grimmwicht** [comment]
Thanks, that would be great. I want to add the german description for this plugin.

Should I close this issue now, or not until you added the line?

**Comment by nickcernis** [comment]
Thanks for your offer to contribute the description translation, @Grimmwicht — that would be very welcome!

I'll leave the issue open until it's resolved, and report back here when then plugin description is ready to translate on WP.org.

**Comment by nickcernis** [comment]
translate.wordpress.org now offers the readme for translation by clicking any of the languages in the “locale” column at https://translate.wordpress.org/projects/wp-plugins/gnu-terry-pratchett/.

I added the text domain and bumped the “Requires at least” WordPress version to 4.6 (to avoid the need to add a redundant `load_plugin_textdomain()` since the plugin contains no translatable strings, following [this advice](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain)).

The page at https://translate.wordpress.org/projects/wp-plugins/gnu-terry-pratchett/ still shows “This plugin is not properly prepared for localization” for reasons that are not clear (no strings aside from the readme, perhaps?). The `#meta-language-packs` Slack channel offers no errors for the latest plugin update.
